"""
Dictionnaire pour renommer les colonnes après export
"""
dictionnaire = {
    "FINESS géographique":"FINESS_GEO",
    "Nom de la structure":"NOM_STRUCTURE",
    "Dép.":"DEP",
    "ET catégorie code":"ET_CAT_CODE",
    "ET catégorie code libellé":"ET_CAT_CODE_NOM",
    "Adresse":"ADR",
    "code postal":"CP",
    "commune":"COMMUNE",
    "x_rgf93":"X_RGF93",
    "y_rgf93":"Y_RGF93",
    "Ej FINESS":"EJ_FINESS",
    "EJ Raison sociale":"EJ_RS",
    "Nom gestionnaire":"NOM_GESTIONNAIRE",
    "Téléphone":"TEL",
    "Nombre de personnels soignant":"NB_PSOIGNANT",
    "Nombre de personnels éducuatift":"NB_PEDUCATIF",
    "Nombre Autres personnels dont administratifs":"NB_PAUTRE",
    "Mail":"MAIL",
    "Fonction":"FONCTION",
    "Nombre de lits installés":"NB_LITS",
    "Nb de personnes suivies au 01/01/2020 (pour toutes les modalités d'accueil)":"NB_PSUIVIES_010120",
    "Médecin coordonnateur":"MEDECIN_COORD",
    "Nombre de personnels total (en nb d'agents au 01/01/2020)":"NB_PTOTAL",
    "Date de saisie":"DATE_SAISIE",
    "Nombre de nouveau cas chez les usagers au sein de l'établissement depuis la dernière saisie":"NOUVEAUX_CAS_ETABLISSEMENT",
    "Nombre de nouveau cas chez les usagers à domicile depuis la dernière saisie":"NOUVEAUX_CAS_DOMICILE",
    "Nombre de nouveau de cas au sein du personnel depuis la dernière saisie":"NOUVEAUX_CAS_PERSONNEL",
    "Nombre de décès à l'établissement":"NB_DECES_ETABLISSEMENT",
    "Nombre de décès à domicile":"NB_DECES_DOMICILE",
    "Nombre de décès à l'hôpital":"NB_DECES_HOPITAL",
    "Personnels absents soignant":"PSOIGNANT_ABS",
    "dont diagnostiqués COVID":"PSOIGNANT_ABS_DCOVID",
    "Personnels absents éducatif":"PEDUCATIF_ABS",
    "dont diagnostiqués COVID.1":"PEDUCATIF_ABS_DCOVID",
    "Personnels absents soignant.1":"PAUTRE_ABS",
    "dont diagnostiqués COVID.2":"PAUTRE_ABS_DCOVID",
    "Nombre de lits/places occupés":"NB_LITS_OCC",
    "Nombre de lits/places disponibles":"NB_LITS_DISPO",
    "Nombre total de situations identifiées comme à risque de rupture à domicile à date":"NB_RISQUE_RUPT_DOM",
    "Nombre total de personnes sans solution à domicile à date":"NB_RUPT_DOM",
    "Demande d'appui de gestion":"DEMANDE_APPUI_GESTION",
    "Autres besoins":"AUTRES_BESOINS",
    "Date de création":"DATE_EXPORT"
}